after_script:
  - docker images

before_script:
  - IMAGE="uphold:$VERSION"

env:
  - VERSION=8.1

language: bash

script:
  - docker build -t "$IMAGE" .
  - docker run "$IMAGE" --version | grep "pgBadger version $VERSION"

services: docker
